Scheduler started
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f29f9397a90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHuQjkYspm0CYr-ZG9xF_h31CB7V-pF118/getMe
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f29f9397d30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHuQjkYspm0CYr-ZG9xF_h31CB7V-pF118/getMe
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f29f9397e80>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHuQjkYspm0CYr-ZG9xF_h31CB7V-pF118/getMe
