Scheduler started
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a1d58b50>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a1d58d30>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32a1d58e80>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
