Scheduler started
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5709bfaf0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5709bfd90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5709bfee0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot378545358:AAHBTmRR02g1B_CDWstn9LqiQHexemPh9tE/getMe
